### ISSUE TITLE
每次刷固件之后，部分配置会重置

### ISSUE THREAD

**Issue by VIKINGYFY** [muink/luci-app-tinyfilemanager#1]
1、右上角的语言设置会重置

2、配置里的用户验证会重置，选项没勾选，但打开需要账号密码验证。

**Comment by muink** [comment]
1. 这部分设定写在本地程序上, 更新后主程序被替换设定就遗失了. 这个是tinyfilemanager设计上的问题, 无法解决
  + https://github.com/prasathmani/tinyfilemanager/blob/master/tinyfilemanager.php#L3
2. 关闭用户验证后需要保存设定并点击上方的重载tinyfilemanager
